name: E2E - Browserstack & Percy

on:
  # if you want the test to be executed reguarly the uncommend the following two lines...
  # schedule:  # Runs at 05:00 UTC on Mon, Tue, Wed, Thu, Fri.
  #  - cron: '0 5 * * 1,2,3,4,5'
   push:
     paths:
       - 'test/**'
       - 'wdio.conf.ts'

permissions: read-all

jobs:
  test:
    name: "E2E Test"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout the repository"
        uses: actions/checkout@v3
      - name: "Use Node 18"
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: "Running npm ci (precise version of npm install)"
        run: npm ci
        env:
          PACKAGES_AUTH_TOKEN: ${{ secrets.PACKAGES_AUTH_TOKEN }}
      - name: "run npm run wdio:percy:bs"
        run: npm run wdio:bs
        env:
          DXP_SAP_EDITION_VERSION: ${{ secrets.DXP_SAP_EDITION_VERSION }}
          SAP_URL: ${{ secrets.SAP_URL }}
          SAP_CLIENT: ${{ secrets.SAP_CLIENT }}
          SAP_USER: ${{ secrets.SAP_USER }}
          SAP_PASSWORD: ${{ secrets.SAP_PASSWORD }}
          BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
          BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
          BROWSERSTACK_OS1: ${{ secrets.BROWSERSTACK_OS1 || 'Windows'}}
          BROWSERSTACK_OS_VERSION1: ${{ secrets.BROWSERSTACK_OS_VERSION1 || '11'}}
          BROWSERSTACK_BROWSER1: ${{ secrets.BROWSERSTACK_BROWSER1 || 'chrome'}}
          BROWSERSTACK_BROWSER_VERSION1: ${{ secrets.BROWSERSTACK_OS_BROWSER_VERSION1 || 'latest'}}
          BROWSERSTACK_PROJECT: ${{ secrets.BROWSERSTACK_PROJECT_NAME }}
          BROWSERSTACK_BUILD_NAME: ${{ secrets.BROWSERSTACK_BUILD_NAME }}
          BROWSERSTACK_BUILD_TAG: ${{ secrets.BROWSERSTACK_BUILD_TAG }}
          BROWSERSTACK_LOCAL: ${{ secrets.BROWSERSTACK_LOCAL }}
